name = "binarytube"
type = "javascript"

account_id = "a681f451b8fcc1d50f7b8b5870b891d2"
workers_dev = true
compatibility_date = "2024-06-01"

[vars]
# environment variables if needed

[[kv_namespaces]]
binding = "META"
id = "8d5bcac71113438097bdfc9ce5ce0852"

[[r2_buckets]]
binding = "VIDEOS"
bucket_name = "binarytube-assets"
